
class ReportHandler: 
	'''
	this class will manage the entire Investigation Report.
	'''

	def __init__(self, path):
		self._path = path
		self._filename = ""
		self._filehandler = ""
		self._br = '\n==============================================================\n\n'


	def InitiateDocument(self, filename, date, ip):
		'''
		this function will create a file and a template of the report.
		including a little background about the investigation.
		'''
		self._filename = self._path +filename

		self._filehandler = open(self._filename+".doc",'wb')
		self._filehandler.write("-------------------------------------------------------------\n")
		self._filehandler.write("\t\t\t Investigation Report\n")
		self._filehandler.write("-------------------------------------------------------------\n\n")
		self._filehandler.write("Background:\n")
		self._filehandler.write("~~~~~~~~~~~\n\n")
		self._filehandler.write("Date of investigation: {}\n\n".format(date))
		self._filehandler.write("Device IP: {}\n\n\n\n\n\n\n".format(ip))
		self._filehandler.write("\t\tGenerated by CIT- Cisco Invastigation Tool\n")
		self._filehandler.write("\t\tBy Omree Benari & Miryam Adjiashvili (c)\n\n\n\n\n\n\n\n\n\n")
		self._filehandler.write(self._br)
		
	def printdata(self, header, body):
		'''
		this function will get the Data and the title to print,
		and will print that in the Investigation file.
		'''

		self._filehandler.write("{}:\n".format(header))
		self._filehandler.write("~~~~~~~~~~~~~~~~~~~~~~\n\n")
		self._filehandler.write("{}\n\n".format(body))
		self._filehandler.write(self._br)
